import { _electron as electron } from 'playwright';
import { mkdir, mkdtemp } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const data = await mkdtemp(path.join(os.tmpdir(), 'anyloader-ui-'));
await mkdir('docs/screenshots', { recursive: true });
const application = process.env.ANYLOADER_APP;
const app = await electron.launch(application ? { executablePath: application, args: [`--data-dir=${data}`] } : { args: ['.', `--data-dir=${data}`] });
try {
  const page = await app.firstWindow();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.waitForSelector('#engine-status:text("Engine ready")');
  await page.waitForTimeout(500); // Capture the fully visible page after its entrance animation.
  await page.screenshot({ path: 'docs/screenshots/downloader.png' });
  await page.getByRole('button', { name: 'Audio only', exact: true }).click();
  await page.locator('#audio-format').selectOption('mp3');
  assert.equal(await page.locator('#audio-format').isVisible(), true);
  assert.equal(await page.locator('#quality').isVisible(), false);
  await page.screenshot({ path: 'docs/screenshots/audio.png' });
  await page.locator('#url').fill('https://example.com/video');
  await page.locator('#download-button').click();
  await page.locator('#link-error').waitFor({ state: 'visible' });
  assert.match(await page.locator('#link-error').textContent(), /YouTube and TikTok/);
  await page.locator('[data-page="settings"]').click();
  await page.locator('#fragments').selectOption('8');
  await page.waitForFunction(async () => (await window.anyloader.state()).settings.fragments === 8);
  await page.locator('#fragments').selectOption('4');
  await page.locator('#concurrent').selectOption('3');
  await page.waitForFunction(() => document.querySelector('#toast').textContent === 'Preferences saved.');
  const state = await page.evaluate(() => window.anyloader.state());
  assert.equal(state.settings.concurrent, 3);
  await page.locator('#concurrent').selectOption('2');
  await page.waitForTimeout(500);
  await page.evaluate(() => { document.querySelector('#toast').hidden = true; });
  await page.screenshot({ path: 'docs/screenshots/settings.png' });
  await page.locator('[data-page="library"]').click();
  await page.getByRole('heading', { name: 'Your collection starts here.' }).waitFor();
  await page.locator('#search').fill('missing');
  await page.locator('[data-page="download"]').click();
  await page.locator('#url').fill('');
  await page.getByRole('button', { name: 'Video', exact: true }).click();
  await page.setViewportSize({ width: 960, height: 720 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  assert.deepEqual(errors, []);
  console.log('UI passed: native launch, video/audio controls, rejected URL, persisted preferences, library, minimum width, renderer isolation.');
} finally { await app.close(); }
